### ISSUE TITLE
Does not support if the game is installed on another drive.

### ISSUE THREAD

**Issue by ChrisF999** [ITS-NIGHTOWL/CSSource-Texture-Installer#1]
It has no support if gmod is installed on another drive.

**Comment by ITS-NIGHTOWL** [comment]
The issue has been known since release and is being addressed next update. A parser for one of the steam save files is just being implemented. Expect update in 1-2 days.

**Comment by CDWimmer** [comment]
It would appear that this is still the case. Any chance of a solution soon?

**Comment by James76931** [comment]
^

**Comment by ITS-NIGHTOWL** [comment]
This project has been inactive for a while now, but I feel it’s about time I start contributing an update to it. I’ll be rewriting the entire project from JavaScript to C in this next version, so expect it to release later this week on my new GitHub account: https://github.com/lamersc . Once the C version is replaced, this repository will be archived and read me redirected to the new version.
