### ISSUE TITLE
Secondary Drive Follow Up

### ISSUE THREAD

**Issue by 0wain** [ITS-NIGHTOWL/CSSource-Texture-Installer#3]
I saw issue #1 asked about installing it to a secondary drive and the issue being closed recently. Is there a follow up on how to do this? Or was the issue closed for another reason?

**Comment by ITS-NIGHTOWL** [comment]
Motivation for this project with me personally is at an all time low, but if you’d be interested in helping develop and continue the texture installer, join here and perhaps we can chat about it: https://discord.gg/rd9k4Qum3K

new GitHub: https://github.com/lydodev
